-- =====================================================
-- MIGRACIÓN V3: Asignación de técnico + índice SLA
-- =====================================================

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- 1. Columna ID_TECNICO en HD_TICKETS (nullable)
ALTER TABLE HELPDESK.HD_TICKETS ADD ID_TECNICO NUMBER;

ALTER TABLE HELPDESK.HD_TICKETS ADD CONSTRAINT FK_TICKET_TECNICO
  FOREIGN KEY (ID_TECNICO)
  REFERENCES HELPDESK.HD_USUARIOS(ID_USUARIO)
  ON DELETE SET NULL;

-- 2. Índice para consultas por técnico asignado
CREATE INDEX HELPDESK.IDX_TICKETS_TECNICO ON HELPDESK.HD_TICKETS(ID_TECNICO);

-- 3. Índice para alertas SLA vencidas
CREATE INDEX HELPDESK.IDX_TICKETS_SLA ON HELPDESK.HD_TICKETS(FECHA_SLA);

-- 4. Actualizar CHK_HIST_ACCION para incluir ASIGNACION
ALTER TABLE HELPDESK.HD_HISTORIAL_TICKETS DROP CONSTRAINT CHK_HIST_ACCION;
ALTER TABLE HELPDESK.HD_HISTORIAL_TICKETS ADD CONSTRAINT CHK_HIST_ACCION CHECK (
  ACCION IN ('CREADO','CAMBIO_ESTADO','COMENTARIO','ASIGNADO','CERRADO','ASIGNACION')
);

-- 5. Verificar
SELECT COLUMN_NAME, DATA_TYPE, NULLABLE
FROM ALL_TAB_COLUMNS
WHERE OWNER = 'HELPDESK' AND TABLE_NAME = 'HD_TICKETS'
ORDER BY COLUMN_ID;

EXIT;
