-- =====================================================
-- MIGRACIÓN V2: Historial, Indexación, Rol PASANTE
-- Zona horaria: America/Guayaquil (UTC-5)
-- Ejecutar como SYS/DBA o con privilegios DBA
-- =====================================================

ALTER SESSION SET "_ORACLE_SCRIPT"=true;

-- 1. TABLA DE HISTORIAL (Trazabilidad de cambios)
-- Registra cada acción sobre un ticket: creación,
-- cambio de estado, comentarios y asignaciones.
-- -------------------------------------------------------
CREATE TABLE HELPDESK.HD_HISTORIAL_TICKETS (
  ID_HISTORIAL    NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  ID_TICKET       NUMBER        NOT NULL,
  ID_USUARIO      NUMBER        NOT NULL,
  ACCION          VARCHAR2(50)  NOT NULL,
  ESTADO_ANTERIOR VARCHAR2(20),
  ESTADO_NUEVO    VARCHAR2(20),
  DETALLE         VARCHAR2(500),
  FECHA           TIMESTAMP     DEFAULT SYSTIMESTAMP NOT NULL,
  CONSTRAINT FK_HIST_TICKET   FOREIGN KEY (ID_TICKET)
    REFERENCES HELPDESK.HD_TICKETS(ID_TICKET)   ON DELETE CASCADE,
  CONSTRAINT FK_HIST_USUARIO  FOREIGN KEY (ID_USUARIO)
    REFERENCES HELPDESK.HD_USUARIOS(ID_USUARIO) ON DELETE CASCADE,
  CONSTRAINT CHK_HIST_ACCION  CHECK (ACCION IN (
    'CREADO', 'CAMBIO_ESTADO', 'COMENTARIO', 'ASIGNADO', 'CERRADO'
  ))
);

-- 2. ÍNDICES DE RENDIMIENTO
-- Cubren los patrones de consulta más frecuentes:
-- filtrado por estado, prioridad, usuario y fecha.
-- -------------------------------------------------------
CREATE INDEX HELPDESK.IDX_TICKETS_ESTADO     ON HELPDESK.HD_TICKETS(ESTADO);
CREATE INDEX HELPDESK.IDX_TICKETS_PRIORIDAD  ON HELPDESK.HD_TICKETS(PRIORIDAD);
CREATE INDEX HELPDESK.IDX_TICKETS_FECHA      ON HELPDESK.HD_TICKETS(FECHA_CREACION DESC);
CREATE INDEX HELPDESK.IDX_TICKETS_USUARIO    ON HELPDESK.HD_TICKETS(ID_USUARIO);
CREATE INDEX HELPDESK.IDX_TICKETS_CATEGORIA  ON HELPDESK.HD_TICKETS(ID_CATEGORIA);
CREATE INDEX HELPDESK.IDX_COMENTARIOS_TICKET ON HELPDESK.HD_COMENTARIOS(ID_TICKET);
CREATE INDEX HELPDESK.IDX_HISTORIAL_TICKET   ON HELPDESK.HD_HISTORIAL_TICKETS(ID_TICKET);
CREATE INDEX HELPDESK.IDX_HISTORIAL_FECHA    ON HELPDESK.HD_HISTORIAL_TICKETS(FECHA DESC);
CREATE INDEX HELPDESK.IDX_USUARIOS_ROL       ON HELPDESK.HD_USUARIOS(ROL);
CREATE INDEX HELPDESK.IDX_USUARIOS_ESTADO    ON HELPDESK.HD_USUARIOS(ESTADO);

-- 3. ROL PASANTE
-- El campo ROL es VARCHAR2 sin CHECK en el export original.
-- Si existe una restricción de CHECK, ejecutar primero:
--   SELECT CONSTRAINT_NAME FROM ALL_CONSTRAINTS
--   WHERE TABLE_NAME = 'HD_USUARIOS' AND OWNER = 'HELPDESK';
-- Luego: ALTER TABLE HELPDESK.HD_USUARIOS DROP CONSTRAINT <nombre>;
--
-- Para PASANTE con estado PENDIENTE (validación):
-- Cuando el ADMIN crea un PASANTE con ESTADO = 'PENDIENTE',
-- el login queda bloqueado hasta que el ADMIN lo aprueba.
-- -------------------------------------------------------

-- Usuario PASANTE de ejemplo (contraseña: Pasante123!)
-- Descomentar si se desea tener un usuario de prueba:
-- INSERT INTO HELPDESK.HD_USUARIOS (EMAIL, PASSWORD_HASH, NOMBRE, ROL, ESTADO)
-- VALUES ('pasante@helpdesk.com',
--   '$2b$10$replaceme',
--   'Pasante Demo', 'PASANTE', 'PENDIENTE');

-- 4. VERIFICAR RESULTADO
-- -------------------------------------------------------
SELECT TABLE_NAME
FROM   ALL_TABLES
WHERE  OWNER = 'HELPDESK'
ORDER BY TABLE_NAME;

SELECT INDEX_NAME, TABLE_NAME
FROM   ALL_INDEXES
WHERE  TABLE_OWNER = 'HELPDESK'
ORDER BY TABLE_NAME, INDEX_NAME;
